import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT=process.cwd();
const PREFIX={actualite:'A',sortie:'S'};
const COLLECTION={actualite:'actualites',sortie:'sorties'};
const pad=n=>String(n).padStart(7,'0');
const sentences=t=>(String(t||'').match(/[^.!?…]+[.!?…]+|[^.!?…]+$/g)||[]).map(s=>s.trim()).filter(Boolean);
const json=async p=>JSON.parse(await fs.readFile(p,'utf8'));
const exists=async p=>{try{await fs.access(p);return true}catch{return false}};

async function nextId(type){const collection=COLLECTION[type];if(!collection)throw new Error('Type inconnu');const dir=path.join(ROOT,collection);await fs.mkdir(dir,{recursive:true});const names=await fs.readdir(dir);const prefix=PREFIX[type];const nums=names.map(x=>new RegExp(`^${prefix}(\\d{7,})$`,'i').exec(x)?.[1]).filter(Boolean).map(Number);return prefix+pad((nums.length?Math.max(...nums):0)+1)}
function normalizePhotos(photos=[]){return photos.map((x,i)=>typeof x==='string'?{src:x,order:i+1}:{...x,order:x.order||i+1})}
function normalizeDocs(documents=[]){return documents.map((x,i)=>typeof x==='string'?{url:x,name:`Document ${i+1}`}:{...x,name:x.name||x.title||`Document ${i+1}`})}
function classify(input){/* Event placement must be explicit/structured, never inferred from a mere mention in prose. */const event=input.event&&input.event.startDate?input.event:null;return{news:input.type==='actualite',upcomingEvents:!!event&&new Date(event.endDate||event.startDate)>=new Date(),sorties:input.type==='sortie'}}
async function rebuildIndex(collection){const dir=path.join(ROOT,collection);await fs.mkdir(dir,{recursive:true});const names=(await fs.readdir(dir,{withFileTypes:true})).filter(x=>x.isDirectory()&&/^[AS]\d{7,}$/i.test(x.name)).map(x=>x.name);const articles=[];for(const id of names){const p=path.join(dir,id,'contenu.json');if(!await exists(p))continue;const a=await json(p);if(a.status!=='draft'&&a.status!=='deleted')articles.push({id,title:a.title,summary:a.summary||'',date:a.date||'',publishedAt:a.publishedAt||a.date||'',category:a.category||'',type:a.type,status:a.status||'published',layoutCode:a.layoutCode,cover:a.photos?.[0]||null,placements:a.placements||{}})}articles.sort((a,b)=>String(b.publishedAt).localeCompare(String(a.publishedAt)));await fs.writeFile(path.join(dir,'index.json'),JSON.stringify({version:1,updatedAt:new Date().toISOString(),articles},null,2)+'\n')}
async function publish(input){if(!PREFIX[input.type])throw new Error('type doit être actualite ou sortie');const id=input.id||await nextId(input.type),collection=COLLECTION[input.type],dir=path.join(ROOT,collection,id);if(await exists(dir))throw new Error(`${id} existe déjà`);const photos=normalizePhotos(input.photos),documents=normalizeDocs(input.documents);const text=String(input.text||'').trim();const content={schemaVersion:1,id,type:input.type,status:input.status||'published',title:input.title,summary:input.summary||'',date:input.date||new Date().toISOString().slice(0,10),publishedAt:input.publishedAt||new Date().toISOString(),category:input.category||'Actualité',layoutCode:input.layoutCode||'H04',text,photos,documents,event:input.event||null,placements:classify(input),metrics:{photoCount:photos.length,documentCount:documents.length,sentenceCount:sentences(text).length,hasGallery:photos.length>9}};await fs.mkdir(path.join(dir,'medias'),{recursive:true});await fs.writeFile(path.join(dir,'contenu.json'),JSON.stringify(content,null,2)+'\n');await fs.writeFile(path.join(dir,'layout.json'),JSON.stringify({layoutCode:content.layoutCode,photos,documents,gallery:photos.length>9},null,2)+'\n');await fs.writeFile(path.join(dir,'media.json'),JSON.stringify({photos,documents},null,2)+'\n');await rebuildIndex(collection);return content}

const inputPath=process.argv[2];if(!inputPath)throw new Error('Usage: node publisher/publish.mjs publication.json');const result=await publish(await json(path.resolve(inputPath)));console.log(JSON.stringify({ok:true,id:result.id,photos:result.photos.length,documents:result.documents.length,gallery:result.metrics.hasGallery},null,2));